linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 150
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - hugeParam
      - wrapperFunc
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - whyNoLint

linters:
  enable-all: true
  disable:
    - maligned
    - gochecknoglobals
    - goimports
    - gomnd
    - wsl
    - godox
    - interfacer
    - godot

run:
  skip-dirs:
    - vendor
    - auth
    - data

issues:
  exclude-rules:
    - text: "weak cryptographic primitive"
      linters:
        - gosec

service:
  golangci-lint-version: 1.23.x # use the fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"
